### ISSUE TITLE
Stacked copycat slab issues

### ISSUE THREAD

**Issue by CodexArchive** [hlysine/create_connected#14] opened 2024-01-09 16:39 UTC
When using the most recent versions of Create (1.20.1-0.5.1.f) and Create: Connected (0.3.1-mc1.20.1), stacking 2 copycat slabs in the same block causes them to act like a single copycat block rather than allowing you to change the appearance of each copycat slab individually. Additionally, when the double slab block is broken, either by wrench or some other tool, it only returns a single copycat slab instead of 2. These both happen regardless of whether the slabs were stacked vertically or horizontally.

**Comment by hlysine** [comment] 2024-01-11 10:12
The first issue is working as intended. Having 2 different materials in a single block requires quite a lot of extra implementation because the current copycat system isn't set up for that. There are other things I want to get to before trying to tackle this one.

The second issue is a small bug related to loot tables which will be fixed in the next update.

**Comment by hlysine** [comment] 2024-01-12 14:27
Fixed in 0.4

**Closed by hlysine** 2024-01-12 14:27 UTC
