### ISSUE TITLE
an incompatibility with fuzs Diagonal Fences mod

### ISSUE THREAD

**Issue by poly-1810** [hlysine/create_connected#33] opened 2024-01-25 17:09 UTC
apparently in the newer versions with copycat fences, diagonal fences removes something the copycat fences needs, either that or diagonal fences needs something that copycat fences need, which causes a crash upon loading worlds
[crash-2024-01-25_11.05.48-server.txt](https://github.com/hlysine/create_connected/files/14055843/crash-2024-01-25_11.05.48-server.txt)
[latest.log](https://github.com/hlysine/create_connected/files/14055847/latest.log)

**Comment by hlysine** [comment] 2024-01-26 03:02
This is a duplicate of #29. I've decided to include a patch that disables diagonal fence behaviors on copycat fences to prevent the crash. It will be up to Diagonal Fences to decide whether they want to support diagonal connections on copycat fences, which use a completely different model system than other fences.

**Comment by MrScrubTZ** [comment] 2024-02-09 21:36
I am not sure if the fix has gone live yet or not, but the Diagonal fence mod and create: connected are not currently compatible.
I just Uninstalled the Diagonal fence mod by Fuzs and I could load into my world with the create: connected mod active finally.

**Comment by hlysine** [comment] 2024-02-10 01:23
The fix is not released yet, so this issue is not closed yet.

**Closed** 2024-02-11 16:02 UTC
Labels: bug, duplicate, type: compat, scope: copycat, level: crash
