### ISSUE TITLE
hello maybe you already knew it but copycat+ have an issue with create connect before the Update it was working but now 

### ISSUE THREAD

**Issue by Hamza95400** [hlysine/create_connected#53] opened 2024-03-09 17:06 UTC
Before the Update it was working but now it doesn't , here de crash :
Create: Connected (create_connected), Version: 0.7.2-mc1.20.1
		Issue tracker URL: https://github.com/hlysine/create_connected/issues
		at TRANSFORMER/create_connected@0.7.2-mc1.20.1/com.hlysine.create_connected.compat.CopycatsManager.copyProperty(CopycatsManager.java:72)
and very my bad if you already knew it and thanks I LOVE YOUR MODS <3

**Comment by hlysine** [comment] 2024-03-11 07:14
There's not enough info in your pasted error message to know what's happening, but this is likely to be a duplicate of #48. That issue has been fixed but I don't have time to release it yet.

**Closed** 2024-03-11 07:14 UTC
Labels: bug, duplicate, type: compat, scope: copycat, level: crash

**Comment by Hamza95400** [comment] 2024-03-11 14:06
Ok thanks we will wait patiently
