### ISSUE TITLE
(Forge, 1.20.1) Fan kinetics with null priority?

### ISSUE THREAD

**Issue by katubug** [hlysine/create_connected#62] opened 2024-04-30 17:06 UTC
I'm on my phone so forgive me for not copying over more of the text. I reported this issue to Create: https://github.com/Creators-of-Create/Create/issues/6428

And they seemed to believe it was an issue with your mod, citing the title. Thanks for your time!

**Comment by hlysine** [comment] 2024-05-01 09:12
Create: Connected does not add any new fan processing types. It seems that another mod is adding null values to the fan processing type registry and causes the game to crash when Create: Connected indirectly initializes the registry. Please try to remove mods that add new fan processing types one by one and see which one is the root cause.

**Comment by katubug** [comment] 2024-05-02 19:23
Oh man, I have no idea what mods those could be, lol. But I'll take a look.
Thank you very much!

**Comment by hlysine** [comment] 2024-05-25 12:48
I have a new theory on what is happening and it may be fixable on Create: Connected's end. Can you test if this dev version fixes the crash?

[UNZIP ME create_connected-0.7.4-mc1.20.1-dev-all.zip](https://github.com/hlysine/create_connected/files/15443493/UNZIP.ME.create_connected-0.7.4-mc1.20.1-dev-all.zip)

**Comment by M0nkeyPr0grammer** [comment] 2024-05-25 16:10
I test launched my pack several times using that dev version and didn't run into the crash. Looks like that fix likely fixed the issue.

**Comment by hlysine** [comment] 2024-05-29 08:00
The fix has been released in Connected v0.8

**Closed by hlysine** 2024-05-29 08:00 UTC
Labels: bug, type: compat, level: crash
