### ISSUE TITLE
Item Silo Multiblock Disassemble Crash

### ISSUE THREAD

**Issue by rhino1998** [hlysine/create_connected#78] opened 2024-09-16 13:00 UTC
Disassembling an assembled contraption containing an item silo multiblock (single silo is fine) causes a ticking block entity crash prevents rejoining the world (if the relevant chunks are loaded). The following setup is sufficient to trigger the crash if you toggle the lever twice.

![2024-09-16_08 57 00](https://github.com/user-attachments/assets/7d512dfd-6932-4f9b-a218-e3a9cad75560)

Here's a stacktrace from a minimal modded install

https://mclo.gs/koFyvmu

Notably this does not affect Fluid Vessels

**Comment by hlysine** [comment] 2024-09-17 03:53
This is caused by contraption changes in Create 0.5.1g. You can enter the world by installing Neruina for now, which will disable the item silo to prevent further crashes.

**Comment by hlysine** [comment] 2024-09-18 04:10
This has been fixed in v0.9.1. It also attempts to fix corrupted worlds, but affected multi-block silos will be split into individual blocks.

**Closed by hlysine** 2024-09-18 04:10 UTC
