### ISSUE TITLE
Forge 1.20.1- v0.7.4 (Crash upon boot)

### ISSUE THREAD

**Issue by M0nkeyPr0grammer** [hlysine/create_connected#63] opened 2024-05-12 15:39 UTC
When booting up my game with Create Connected included I get this error: 
![image](https://github.com/hlysine/create_connected/assets/86218191/42ab0a7d-e21e-405c-a968-138949c6c022)

Along with the crash report: 
[crash-2024-05-12_10.35.50-fml.txt](https://github.com/hlysine/create_connected/files/15286853/crash-2024-05-12_10.35.50-fml.txt)

*Note this doesn't happen every time I launch, relaunching after the crash seems to resolve it occasionally.

**Comment by hlysine** [comment] 2024-05-25 12:22
This is a duplicate of #62. Please add additional info there.

**Closed by hlysine** 2024-05-25 12:22 UTC
