### ISSUE TITLE
Linked transmitter mulfunction

### ISSUE THREAD

**Issue by tawan256** [hlysine/create_connected#25] opened 2024-01-21 10:28 UTC
When linked transmitter is attatched to button, it won't display an item frequency. Also, when pressed, reciever in the same frequency won't stop recieving signal until transmitter's broken

Create connected 0.5.1
MC 1.19.2

**Comment by tawan256** [comment] 2024-01-21 10:39
Another issue, when attatched to analog lever, it's power level can't be decreased

**Comment by hlysine** [comment] 2024-01-21 11:02
The issue with buttons is limited to stone buttons in 1.18/1.19 only and is caused by an API change from MC 1.19.2 to 1.20.1. The fix will be released in the next update.

The issue with the analog lever happens in all versions and needs further investigation. You can only decrease its power when you are not holding anything.

**Comment by hlysine** [comment] 2024-01-24 11:48
Both fixes are released in 0.6

**Closed by hlysine** 2024-01-24 11:48 UTC
Labels: bug, scope: redstone, level: minor
