### ISSUE TITLE
Crashes client packs with various other Create add-ons

### ISSUE THREAD

**Issue by MadSciSlack** [hlysine/create_connected#24] opened 2024-01-20 02:15 UTC
Updating to Create Connected version 0.5.1 clashes with other add-ons.  Initially it was Create Jetpack that crashed.  Once Jetpack was disabled, Create: Slice and Dice had the same issue.  My server seems to launch, but the client crashes.

These issues are not present when launching with the previous version (0.4.2).  Client and server both launch cleanly with the previous version installed, but not the latest.

This is the crash log from before I disabled Create Jetpack.  The one I glanced at for Slice and Dice was largely the same.

[crash-2024-01-19_18.13.42-client.txt](https://github.com/hlysine/create_connected/files/13996267/crash-2024-01-19_18.13.42-client.txt)

**Comment by hlysine** [comment] 2024-01-20 08:03
Please try removing `mixinextras-forge-0.2.0.jar` and see if the issue is fixed. C:Connected 0.5+ comes with MixinExtras included.

**Comment by MadSciSlack** [comment] 2024-01-21 23:18
I'm happy to help test this to determine if things work better without MixinExtras, but I have further concerns.

If I'm not mistaken, this fix won't work for modpacks that download from CF as C:Connected will install MixinExtras when downloaded.  

Is there potential to remove MixinExtras from C:Connected (formally) in future versions?  Provided compatibility improves as expected, this would allow pack makers to include it in packs with more add-ons.

**Comment by hlysine** [comment] 2024-01-22 00:08
Some of the new patches introduced in C:Connected require MixinExtras to work. It is not a formal dependency that you have to download separately on CF. Instead, C:Connected provides its own copy of MixinExtras through a technique called jar-in-jar, similar to how Create bundles Flywheel in its own jar.

Since C:Connected bundles the newest version of MixinExtras (0.3.3), it may conflict with v0.2.0 that you have installed according to your logs. It's only a theory though, since I can't find much documentation on how to deploy MixinExtras in mods.

**Comment by MadSciSlack** [comment] 2024-01-22 23:56
I would recommend my pack, but it isn't public yet.  Maybe "All of Create"?  It's in 1.19 as well and they brag about having "TONS of Create add-ons".  I have not tested it though.  

Either way I'll do some more testing and provide feedback.  I have a private dev server at my disposal as well, so things that work client side also get tested server side.

I've been tied up for the past few days with other mods, but will be getting back to my modpack and this issue possibly today.

Cheers,

Slack

**Comment by MadSciSlack** [comment] 2024-01-23 00:23
Bad news... MixinExtras 0.2.0 has to be bundled jar-to-jar with another mod the same way that 0.3.3 is bundled with C:Connected.  I cannot find or access the jar file, so this is my assumption.  I'm at a bit of a loss, as I can't tell what is providing MixinExtras 0.2.0.

With no way to remove MixinExtras, I have little choice but to either keep C:Connected at V0.4.2 (runs but has some warnings server-side) or remove it altogether.  Currently I have V0.4.2 running, and can _hope_ that whatever is using 0.2.0 updates to a newer MixinExtras.

If you have any insights or ideas, I'm all ears.

**Comment by hlysine** [comment] 2024-01-23 01:17
I've tested All of Create before releasing v0.5 and no errors were triggered. 

I still have a few ideas on how to fix this, such as downgrading MixinExtras to 0.2.0 and changing things in the build script. Do you mind if I send a few dev versions for you to test in your private modpack? They will be available later today/tomorrow.

**Comment by hlysine** [comment] 2024-01-23 11:06
[UNZIP ME create_connected-0.5.1-dev-mc1.20.1-all.zip](https://github.com/hlysine/create_connected/files/14022652/UNZIP.ME.create_connected-0.5.1-dev-mc1.20.1-all.zip)

I've updated MixinExtras to 0.3.5. Please test if this version fixes the crash.

**Comment by GamingEinstein** [comment] 2024-01-23 19:34
> [UNZIP ME create_connected-0.5.1-dev-mc1.20.1-all.zip](https://github.com/hlysine/create_connected/files/14022652/UNZIP.ME.create_connected-0.5.1-dev-mc1.20.1-all.zip)
>
> I've updated MixinExtras to 0.3.5. Please test if this version fixes the crash.

I tested this personally with my modpack, which was also having problems with the latest version of the mod, and it seems to have booted perfectly fine

**Comment by hlysine** [comment] 2024-01-24 11:45
Should be fixed in 0.6. Please open a new issue if there are any further issues.

**Closed by hlysine** 2024-01-24 11:45 UTC
Labels: bug, type: mixin, level: crash
